-- MySQL Script generated by MySQL Workbench
-- Tue Oct 22 08:42:21 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- DATABASE mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- DATABASE pagina13
-- -----------------------------------------------------
DROP DATABASE IF EXISTS `pagina13` ;

-- -----------------------------------------------------
-- DATABASE pagina13
-- -----------------------------------------------------
CREATE DATABASE IF NOT EXISTS `pagina13` DEFAULT CHARACTER SET utf8 ;
USE `pagina13` ;

-- -----------------------------------------------------
-- Table `pagina13`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`users` (
  `idUsers` MEDIUMINT UNSIGNED NOT NULL,
  `name` CHAR(90) NOT NULL,
  `surname` CHAR(90) NOT NULL,
  `email` CHAR(45) NOT NULL,
  `pass` MEDIUMTEXT NOT NULL,
  `bTheme` BINARY NOT NULL DEFAULT 0,
  `img` MEDIUMTEXT NULL DEFAULT NULL,
  `desc` TINYTEXT NULL DEFAULT NULL,
  `create_at` DATETIME NOT NULL,
  `update_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`idUsers`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pagina13`.`reco`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`reco` (
  `idReco` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `key` SMALLINT UNSIGNED NOT NULL,
  `developement_at` DATETIME NOT NULL,
  `users_idUsers` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idReco`, `users_idUsers`),
  INDEX `fk_accountRecovery_Users1_idx` (`users_idUsers` ASC) ,
  CONSTRAINT `fk_accountRecovery_Users1`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `pagina13`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pagina13`.`cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`cat` (
  `idCat` BIT(10) NOT NULL,
  `name` CHAR(45) NOT NULL,
  PRIMARY KEY (`idCat`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pagina13`.`pos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`pos` (
  `idPos` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` CHAR(90) NOT NULL,
  `subtitle` TINYTEXT NOT NULL,
  `desc` MEDIUMTEXT NOT NULL,
  `img` MEDIUMTEXT NOT NULL,
  `isArc` BINARY NOT NULL DEFAULT 0,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  `users_idUsers` MEDIUMINT UNSIGNED NOT NULL,
  PRIMARY KEY (`idPos`, `users_idUsers`),
  INDEX `fk_Posts_Users1_idx` (`users_idUsers` ASC) ,
  CONSTRAINT `fk_Posts_Users1`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `pagina13`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pagina13`.`fav`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`fav` (
  `users_idUsers` MEDIUMINT UNSIGNED NOT NULL,
  `pos_idPos` MEDIUMINT UNSIGNED NOT NULL,
  `create_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`users_idUsers`, `pos_idPos`),
  INDEX `fk_Posts_has_Users_Users1_idx` (`users_idUsers` ASC) ,
  INDEX `fk_Posts_has_Users_Posts1_idx` (`pos_idPos` ASC) ,
  CONSTRAINT `fk_Posts_has_Users_Posts1`
    FOREIGN KEY (`pos_idPos`)
    REFERENCES `pagina13`.`pos` (`idPos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_has_Users_Users1`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `pagina13`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pagina13`.`pos_cat`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`pos_cat` (
  `pos_idPos` MEDIUMINT UNSIGNED NULL,
  `cat_idCat` BIT(10) NULL,
  PRIMARY KEY (`pos_idPos`, `cat_idCat`),
  INDEX `fk_Posts_has_Categories_Categories1_idx` (`cat_idCat` ASC) ,
  INDEX `fk_Posts_has_Categories_Posts1_idx` (`pos_idPos` ASC) ,
  CONSTRAINT `fk_Posts_has_Categories_Categories1`
    FOREIGN KEY (`cat_idCat`)
    REFERENCES `pagina13`.`cat` (`idCat`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_has_Categories_Posts1`
    FOREIGN KEY (`pos_idPos`)
    REFERENCES `pagina13`.`pos` (`idPos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `pagina13`.`rece`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pagina13`.`rece` (
  `users_idUsers` MEDIUMINT UNSIGNED NOT NULL,
  `pos_idPos` MEDIUMINT UNSIGNED NOT NULL,
  `created_at` DATETIME NOT NULL,
  `updated_at` DATETIME NULL DEFAULT NULL,
  `deleted_at` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`users_idUsers`, `pos_idPos`),
  INDEX `fk_Posts_has_Users_Users1_idx` (`users_idUsers` ASC) ,
  INDEX `fk_Posts_has_Users_Posts1_idx` (`pos_idPos` ASC) ,
  CONSTRAINT `fk_Posts_has_Users_Posts10`
    FOREIGN KEY (`pos_idPos`)
    REFERENCES `pagina13`.`pos` (`idPos`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Posts_has_Users_Users10`
    FOREIGN KEY (`users_idUsers`)
    REFERENCES `pagina13`.`users` (`idUsers`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;